qpaas:
  gateway:
    id: jiangsusuyanjingshe220211206162844
    password: fef371b378454b548ec05921971ae75c
    username: jiangsusuyanjingshe220211206162844
  mqtt:
    url: tcp://iot.qpaas.com:1883

yunyun:
  url:
    ip: http://cloud.anylink.io:8600
    token_url: ${yunyun.url.ip}/user/getToken
    agentList_url: ${yunyun.url.ip}/agentList/pagination
    currentdata_url: ${yunyun.url.ip}/currentdata/pagination
  config:
    tenantEname: jingshen
    username: anyuan
    password: 13851778645
    serialNumber: jingshen
    deviceIds: 1444563972,1444563969
    agentId: 1410707





logging:
  file:
    max-history: 1
    max-size: 10MB
    name: ./log/iot.log
    total-size-cap: 1GB
  level:
    com:
      qpaas:
        service: info
      qycloud:
        iot: info
    root: info
  pattern:
    file: '{"time":"%date{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","code":"%logger{40}\(%file:%line\)","product_line":"iot","sid":"%date{ddHHmmssSSS}.${PID}.%t","msg":"%msg","context":"%throwable"}%n'
