spring:
  profiles:
    active: chengdongzhan
#    active: ergongsizhan
#    active: zhangxingzhan

qpaas:
  gateway:
    id: jiangsusuyanjingshe220211206163052
    password: 3251183ced7a491f88acdfa1a8389aae
    username: jiangsusuyanjingshe220211206163052
  mqtt:
    url: tcp://iot.qpaas.com:1883

yunyun:
  url:
    ip: http://cloud.anylink.io:8600
    token_url: ${yunyun.url.ip}/user/getToken
    agentList_url: ${yunyun.url.ip}/agentList/pagination
    currentdata_url: ${yunyun.url.ip}/currentdata/pagination
  config:
    tenantEname: jingshen
    username: anyuan
    password: 13851778645
    serialNumber: jingshen
    deviceIds: 1444563972,1444563969  #设备id
    agentId: 1410707  #网关id
    deviceIdsFilter: false  #是否只采集指定的设备id
    sensorFilter: false  #是否只采集指定的点位名称
    filePath: /     #点位名称所在文件夹，点位名称格式必须以  ~隔开，例子见 sensor.txt






logging:
  file:
    max-history: 1
    max-size: 10MB
    name: ./log/iot.log
    total-size-cap: 1GB
  level:
    com:
      qpaas:
        service: info
      qycloud:
        iot: info
    root: info
  pattern:
    file: '{"time":"%date{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","code":"%logger{40}\(%file:%line\)","product_line":"iot","sid":"%date{ddHHmmssSSS}.${PID}.%t","msg":"%msg","context":"%throwable"}%n'

